# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jys', '0003_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.IntegerField(),
        ),
    ]
