# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-27 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jys', '0004_auto_20160519_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.IntegerField()),
                ('paper_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='be_collected',
            field=models.CharField(blank=True, max_length=10, verbose_name='\u96be\u5ea6'),
        ),
        migrations.AddField(
            model_name='question',
            name='be_reposted',
            field=models.CharField(blank=True, max_length=10, verbose_name='\u96be\u5ea6'),
        ),
        migrations.AddField(
            model_name='question',
            name='be_selected',
            field=models.CharField(blank=True, max_length=10, verbose_name='\u96be\u5ea6'),
        ),
        migrations.AddField(
            model_name='question',
            name='be_supported',
            field=models.CharField(blank=True, max_length=10, verbose_name='\u96be\u5ea6'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=500, verbose_name='\u7b54\u6848'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='\u9898\u76ee\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_a',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u9009\u9879A'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_b',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u9009\u9879B'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_c',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u9009\u9879C'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_d',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u9009\u9879D'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_e',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u9009\u9879E'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_f',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u9009\u9879F'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(blank=True, max_length=10, verbose_name='\u96be\u5ea6'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='\u9898\u76ee\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(blank=True, max_length=500, verbose_name='\u9898\u76ee\u5185\u5bb9'),
        ),
    ]
