# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-28 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jys', '0006_auto_20160628_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duoxuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(blank=True, max_length=20, verbose_name='\u9898\u76ee\u7f16\u53f7')),
                ('category_id', models.CharField(blank=True, max_length=10, verbose_name='\u9898\u76ee\u7c7b\u578b')),
                ('subject', models.CharField(blank=True, max_length=500, verbose_name='\u9898\u76ee\u5185\u5bb9')),
                ('choice_a', models.CharField(blank=True, max_length=100, verbose_name='\u9009\u9879A')),
                ('choice_b', models.CharField(blank=True, max_length=100, verbose_name='\u9009\u9879B')),
                ('choice_c', models.CharField(blank=True, max_length=100, verbose_name='\u9009\u9879C')),
                ('choice_d', models.CharField(blank=True, max_length=100, verbose_name='\u9009\u9879D')),
                ('choice_e', models.CharField(blank=True, max_length=100, verbose_name='\u9009\u9879E')),
                ('choice_f', models.CharField(blank=True, max_length=100, verbose_name='\u9009\u9879F')),
                ('difficulty', models.CharField(blank=True, max_length=10, verbose_name='\u96be\u5ea6')),
                ('answer', models.CharField(blank=True, max_length=500, verbose_name='\u7b54\u6848')),
                ('be_supported', models.CharField(blank=True, max_length=10, verbose_name='\u96be\u5ea6')),
                ('be_collected', models.CharField(blank=True, max_length=10, verbose_name='\u96be\u5ea6')),
                ('be_selected', models.CharField(blank=True, max_length=10, verbose_name='\u96be\u5ea6')),
                ('be_reposted', models.CharField(blank=True, max_length=10, verbose_name='\u96be\u5ea6')),
            ],
        ),
    ]
