# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-28 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jys', '0010_jianda'),
    ]

    operations = [
        migrations.CreateModel(
            name='lunshu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(blank=True, max_length=20, verbose_name='\u9898\u76ee\u7f16\u53f7')),
                ('category_id', models.CharField(blank=True, max_length=10, verbose_name='\u9898\u76ee\u7c7b\u578b')),
                ('subject', models.CharField(blank=True, max_length=500, verbose_name='\u9898\u76ee\u5185\u5bb9')),
                ('difficulty', models.CharField(blank=True, max_length=10, verbose_name='\u96be\u5ea6')),
                ('answer', models.CharField(blank=True, max_length=500, verbose_name='\u7b54\u6848')),
                ('be_supported', models.CharField(blank=True, max_length=10, verbose_name='\u70b9\u8d5e')),
                ('be_collected', models.CharField(blank=True, max_length=10, verbose_name='\u6536\u85cf')),
                ('be_selected', models.CharField(blank=True, max_length=10, verbose_name='\u91c7\u7eb3')),
                ('be_reposted', models.CharField(blank=True, max_length=10, verbose_name='\u8f6c\u53d1')),
            ],
        ),
    ]
